### ISSUE TITLE
refresh the current chess partie

### ISSUE THREAD

**Issue by antiproton** [jsonchess/lightsquare#99]
Error response
Error code 404.
Message: File not found.
Error code explanation: 404 = Nothing matches the given URI.

**Comment by gushogg-blake** [comment]
This is because the app uses pushState and the HTML5 history API to make the URLs look nice - you are at /game/whatever, but obviously there is no file called that, so if you request the page again the SimpleHTTPServer will give you a 404.  Navigating around the site doesn't make extra requests for each page - it's all handled client-side - but pressing F5 does, which is why you get the error then.  When I install it I use Apache with URL rewriting, so that Apache knows to serve /index.html for any URL.  Then the same page is served every time and the client-side code figures out what to do based on the URL.  There is an example Apache configuration in the README.
